 var  CONFIG = {};
CONFIG.JWT = {
    SECRET: 'TEST_SECRET'
}
CONFIG.MODE = 'DEV';
CONFIG.PROD_MODE = CONFIG.MODE === 'DEV' ? false: true;
CONFIG.IS_CERT_AUTH_ENABLED = false;
CONFIG.CURRENCY= process.env.NEXT_PUBLIC_CURRENCY_LABEL || "QAR";
CONFIG.TEST_GATEWAY = {
    BASEURL: process.env.NEXT_PUBLIC_TEST_GATEWAY_URL || "https://amexmena.gateway.mastercard.com",
    API_VERSION: process.env.NEXT_PUBLIC_API_VERSION || "62",
    USERNAME: 'merchant.' + process.env.NEXT_PUBLIC_USERNAME || "TEST9767612138",
    // USERNAME: "merchant.TEST9767612138",
    PASSWORD:  "Aemempgs@1" ,
    MERCHANTID:  "TEST9767612138",
    AMEX_TOKEN : process.env.NEXT_PUBLIC_AMEX_TOKEN || "bWVyY2hhbnQuVEVTVDk3Njc2MTIxMzg6MDk0YmY0ZmZlNWMxYjRmOWU1NWY1NmMxNWFjNTM0ZTE=",
    DB_BASE_URL : process.env.NEXT_PUBLIC_DB_API_BASE_URL,
    AMEX_REDIRECT_URL :  process.env.NEXT_PUBLIC_REDIRECT_URL
};
CONFIG.PKI_GATEWAY = {
    BASEURL: process.env.NEXT_PUBLIC_BASEURL || "https://amexmena.gateway.mastercard.com" ,
    API_VERSION: process.env.NEXT_PUBLIC_API_VERSION || "62",
    // MERCHANTID:process.env.USERNAME || "TESTUSER"
    MERCHANTID:"TESTUSER"
}
CONFIG.WEBHOOKS = {
    WEBHOOKS_NOTIFICATION_SECRET : process.env.NEXT_PUBLIC_WEBHOOKS_NOTIFICATION_SECRET,
    WEBHOOKS_NOTIFICATION_FOLDER : 'webhooks-notifications'
}
CONFIG.SSL_FILES = {
    CRT: process.env.NEXT_PUBLIC_SSL_CRT_PATH,
    KEY: process.env.NEXT_PUBLIC_SSL_KEY_PATH
}
module.exports = CONFIG;